---
- name: Jenkins creation
  hosts: localhost
  connection: local
  vars:
    A: "{{ jenkins_username }}"
    B: "{{ jenkins_password }}"

  tasks:
    - name: Get Jenkins crumb
      uri:
       token: 11453ddd7a8ba85b3248bf05374cc7d40e
       force_basic_auth: yes
       url: "http://13.127.63.250:8080/crumbIssuer/api/json"
       return_content: yes
      register: crumb_token
      until: crumb_token.content.find('Please wait while Jenkins is getting ready') == -1
      retries: 10
      delay: 5

    - name: Set crumb token
      set_fact:
        crumb: "{{ crumb_token.json.crumbRequestField }}={{ crumb_token.json.crumb }}"

    - name: Queue build of a project in Jenkins
      uri:
       body_format: json
       body: "{{ input }}"
       header:
         Content-Type: "application/x-www-form-urlencoded"
       url: http://13.127.63.250:8080/job/Devops/job/{{ job_name }}/buildWithParameters?token=build.default=on&{{ crumb }}
       method: POST
       token: 11453ddd7a8ba85b3248bf05374cc7d40e
       return_content: yes
       force_basic_auth: true
       status_code: 201
      register: job_status

    - debug:
        var: job_status

    - name: query jenkins job queue to see if it has been able to start a build
      block:
        - name: poll jenkins JOB QUEUE every 3 seconds for configured number of attempts to get the number from the job queue
          uri:
             force_basic_auth: yes
             headers:
               Content-Type: "application/json"
             method: GET
             return_content: yes
             timeout: 3
             url: "{{job_status.location}}/api/json"
             token: 11453ddd7a8ba85b3248bf05374cc7d40e
          register: poll_result
          until: poll_result.json.executable.number|default(0)|int > 0
          retries: 10
          delay: 10

      rescue:
        - name: Fail because we could not query the jenkins job queue successfully
          fail:
            msg: "Error, could not query the jenkins job queue"


    - name: check for jenkins job success
      block:
        - name: show the build job url detected above
          debug:
           msg: "Build job is at "

        - name: now poll jenkins JOB every 3 seconds for configured number of attempts to check if the job was actually successful
          uri:
           force_basic_auth: yes
           headers:
            Content-Type: "application/json"
           method: GET
           token: 11453ddd7a8ba85b3248bf05374cc7d40e
           timeout: 3
           url: "http://13.127.63.250:8080/job/Devops/job/{{ job_name }}/lastBuild/api/json?tree=result"
          register: build_job_result
          until: build_job_result.json.result == 'SUCCESS'
          retries: 100
          delay: 10

        - debug:
            msg: "{{ build_job_result.json.result }}"

        - name: show the build job url detected above
          debug:
            var: "{{ build_job_result }}"
      rescue:

        - name:
          fail:
            msg: "Build job failed"
